name: ig_ui
description:
publish_to:
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/InstagramLogo.png
    - assets/images/User.png
    - assets/icons/Back.png
    - assets/icons/Shape.png
    - assets/images/Oval_Profile.png
    - assets/icons/Shape_down.png
    - assets/icons/Add_Chat.png
    - assets/icons/Search_Icon.png
    - assets/images/Profile1.png
    - assets/images/Profile2.png
    - assets/images/Profile3.png
    - assets/images/Profile4.png
    - assets/images/Profile5.png
    - assets/images/Profile6.png
    - assets/images/Profile7.png
    - assets/images/Profile8.png
    - assets/icons/Icon_Camera.png
    - assets/icons/Camera_White.png
